[package]
name = "kaw"
version = "0.1.6"
edition = "2024"

[dependencies]
deno_core = { version = "0.409.0", default-features = false, features = ["reactor-tokio"] }
deno_error = "0.7.1"
tokio = { version = "1.52.3", default-features = false }

[dev-dependencies]
assert_cmd = "2.2.2"

[build-dependencies]
deno_core = "0.409.0"

[profile.release]
codegen-units = 1
lto = true
panic = "abort"
strip = true
