[package]
name = "kaw"
version = "0.1.0"
edition = "2021"

[dependencies]
deno_core = "0.311.0"
tokio = { version = "1.40.0", features = ["full"] }

[dev-dependencies]
assert_cmd = "2.0.16"

[build-dependencies]
deno_core = "0.311.0"
